---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: goerli
  labels:
    app: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: lachy0x/portfolio:v1.0.0
          ports:
            - containerPort: 80
          imagePullPolicy: Always
